### ISSUE TITLE
Enforcing policies and governance for Kubernetes workloads

### ISSUE THREAD

**Issue by danielepolencic** [Hubstation/newsletter#13]
https://learnk8s.io/kubernetes-policies

**Comment by saiyam1814** [comment]
Will be added, thanks

**Comment by danielepolencic** [comment]
Thank you!

**Comment by sangam14** [comment]
![Hub Station](https://user-images.githubusercontent.com/21982562/88934865-bf0a2400-d29e-11ea-8827-c07e9da10131.png)

@saiyam1814

**Comment by saiyam1814** [comment]
Added
