### ISSUE TITLE
attached banner for aug newsletter 

### ISSUE THREAD

**Issue by sangam14** [Hubstation/newsletter#33]
![Aug- HubStation](https://user-images.githubusercontent.com/21982562/91734011-fafb1680-ebc7-11ea-8596-dc371d322c12.png)
@saiyam1814

**Comment by sangam14** [comment]
---
layout: post
title: August 2020 - Hubstation Newsletter 
tags: [Aug, Hubstation]
---

                            
![Hits](https://hitcounter.pythonanywhere.com/count/tag.svg?url=https%3A%2F%2Fhubstation.github.io%2Fnewsletter%2F2020%2F08%2F31%2FAugust.html)

add to august page at top of the .md

**Comment by sangam14** [comment]
```





---
layout: post
title: August 2020 - Hubstation Newsletter 
tags: [Aug, Hubstation]
---

                            
![Hits](https://hitcounter.pythonanywhere.com/count/tag.svg?url=https%3A%2F%2Fhubstation.github.io%2Fnewsletter%2F2020%2F08%2F31%2FAugust.html)

```

**Comment by saiyam1814** [comment]
Done
