### ISSUE TITLE
logo adding .

### ISSUE THREAD

**Issue by sangam14** [Hubstation/newsletter#8]
![Screenshot 2020-06-30 at 10 41 56 PM](https://user-images.githubusercontent.com/21982562/86156267-4db24680-bb23-11ea-9125-ff7aa291b0e9.png)
@saiyam1814 add under asssets/img

**Comment by sangam14** [comment]
@ajeetraina do you have access  to this repo . and you add above logo in assets/img dir

**Comment by saiyam1814** [comment]
Done
